const SINGLE_FILE_PREFIX = "single-filez-";
const COMMENT_HEADER = "Page saved with SingleFileZ";
const SINGLE_FILE_SIGNATURE = "SingleFileZ";
const WAIT_FOR_USERSCRIPT_PROPERTY_NAME = "_singleFileZ_waitForUserScript";

export {
	SINGLE_FILE_PREFIX,
	COMMENT_HEADER,
	SINGLE_FILE_SIGNATURE,
	WAIT_FOR_USERSCRIPT_PROPERTY_NAME
};